/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 museum.glb 
*/
import mscene from "../assets/3d/museum.glb";
import { useGLTF } from "@react-three/drei";

export default function Museum({ scale, position, ...props }) {
    const { nodes, materials } = useGLTF(mscene);
    return (
        <group {...props} dispose={null} scale={scale} position={position}>
            <mesh
                geometry={nodes.Tessellation005.geometry}
                material={materials[" brown wood"]}
                position={[-86.375, 37.799, -220.419]}
                scale={[1, 0.765, 1]}
            />
            <mesh
                geometry={nodes.Tessellation004.geometry}
                material={materials[" brown wood"]}
                position={[-66.532, 37.128, -229.788]}
                rotation={[0, 1.571, 0]}
                scale={[1, 0.765, 1]}
            />
            <mesh
                geometry={nodes.Tessellation006.geometry}
                material={materials[" brown wood"]}
                position={[-97.297, 36.815, -239.284]}
                rotation={[Math.PI, -1.339, Math.PI]}
                scale={[1, 0.746, 1]}
            />
            <mesh
                geometry={nodes.ingoro_2_preserve007.geometry}
                material={materials["Bamboo.002"]}
                position={[-70.369, 93.339, -236.781]}
            />
            <mesh
                geometry={nodes.SM_StrawMat372_M_StrawMat372_0001.geometry}
                material={materials.M_StrawMat372}
                position={[-123.472, 10.8, -338.319]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={0.225}
            />
            <mesh
                geometry={nodes.Plane005.geometry}
                material={materials["Dirt Ground Material"]}
                position={[-63.846, 6.909, -223.566]}
                scale={231.343}
            />
            <group
                position={[-71.119, 94.917, -237.016]}
                scale={[1.376, 1.375, 1.428]}
            >
                <mesh
                    geometry={nodes.Mesh001_1.geometry}
                    material={materials.brown}
                />
                <points
                    geometry={nodes.Mesh001_2.geometry}
                    material={materials.brown}
                />
                <mesh
                    geometry={nodes.Mesh001_3.geometry}
                    material={materials.brown}
                />
                <points
                    geometry={nodes.Mesh001_4.geometry}
                    material={materials.brown}
                />
            </group>
            <mesh
                geometry={nodes.Mesh002.geometry}
                material={materials["brown._lighter"]}
                position={[-205.641, 26.399, -193.465]}
                rotation={[0, -1.262, 0]}
                scale={1.406}
            >
                <mesh
                    geometry={nodes.GN_Instance_1.geometry}
                    material={materials["brown._lighter"]}
                />
            </mesh>
            <mesh
                geometry={nodes.Torus035.geometry}
                material={materials["Material.007"]}
                position={[-206.199, 25.803, -279.551]}
                rotation={[0, -0.897, 0]}
                scale={1.406}
            />
            <mesh
                geometry={nodes.Cylinder.geometry}
                material={materials[" brown wood"]}
                position={[-68.726, 113.182, -236.967]}
                scale={[1.788, 102.78, 1.788]}
            />
        </group>
    );
}
